program: train_nerf2d.py
entity: romeu
project: NeRF2D
description: Depth experiment - All cameras
name: depth_experiment_all_views
method: grid

parameters:

  # run for all datasets
  data.artifact:
    values: [ bunny:latest, cube:latest, cube_convex:latest ]

  # run for all sparsity levels
  +view_sparsity:
    values: [ 2_view, 5_view, 10_view, all_views ]

  # run with and without depth supervision
  model.use_depth_supervision:
    values: [ true, false ]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}