seed: 0
dev_run: false

defaults:
  - override hydra/launcher: basic
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

wandb:
  run_name: null
  job_type: train
  project: NeRF2D

trainer:
  max_epochs: 1000
  min_epochs: 0
  overfit_batches: false
  check_val_every_n_epoch: 10
  log_every_n_steps: 1
  patience: 30

data:
  artifact: bunny:v1
  batch_size: 1000
  camera_subset: false
  camera_subset_n: 5

model:
  t_near: 0.1
  t_far: 12
  n_steps: 200
  n_freqs_pos: 8
  n_freqs_dir: 5
  n_layers: 6
  d_hidden: 128
  chunk_size: 30000
  lr: 1e-4
  depth_loss_weight: 0.25
  depth_sigma: 0.1
  use_depth_supervision: true
